highlights: pygments
lsi: false
exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "best-albums.lua",
    "best-albums.tgz",
    "write_gemini_index.rb",
    "text-gemini.tmpl",
    "vendor",
  ]
destination: _site

collections:
  albums:
